import AsyncHandler from "express-async-handler";

const getFleet = AsyncHandler(async (req, res) => {
  const { message, phoneNumber } = req.body;
  res.status(201).json({
    success: true,
    message: "Fleet data fetched successfully",
    details:{
    message,
    phoneNumber
    },
    data: {
      UserType: ["Transporter", "Forwarder", "Admin"],
      Destinations: [
        {
          Destination: "Kollam",
          Kilometer: "200",
          "20FTRate": 18000,
          "40FTRate": 20000,
        },
        {
          Destination: "Kozhikkod",
          Kilometer: "200",
          "20FTRate": 18000,
          "40FTRate": 20000,
        },
      ],
      Transporter: {
        Name: "ABC Transporter",
        Trucks: [
          {
            TruckNumber: "KL-07-AB-1234",
            TruckType: "20 FT",
            CurrentStatus: "In Queue",
            QueuePosition: 3,
            BookingTime: "20 July 2025, 11:30 AM",
            BookingId: "FQ-BK-4582",
            Forwarder: null,
            Destination: null,
            TripRate: null,
            ContactPerson: null,
            ContactNumber: null,
          },
          {
            TruckNumber: "KL-07-AB-1111",
            TruckType: "20 FT",
            CurrentStatus: "Open",
            QueuePosition: null,
            BookingTime: null,
            BookingId: null,
            Forwarder: null,
            Destination: null,
            TripRate: null,
            ContactPerson: null,
            ContactNumber: null,
          },
          {
            TruckNumber: "KL-07-AB-1211",
            TruckType: "40 FT",
            CurrentStatus: "Open",
            QueuePosition: null,
            BookingTime: null,
            BookingId: null,
            Forwarder: null,
            Destination: null,
            TripRate: null,
            ContactPerson: null,
            ContactNumber: null,
          },
          {
            TruckNumber: "KL-07-AB-0000",
            TruckType: "20 FT",
            CurrentStatus: "Allotted",
            QueuePosition: null,
            BookingTime: "20 July 2025, 11:30 AM",
            BookingId: "FQ-BK-4582",
            Forwarder: "ABC Logistics Pvt Ltd",
            Destination: "Coimbatore",
            TripRate: 18000,
            ContactPerson: "Rajeev",
            ContactNumber: "9847000000",
          },
        ],
      },
      Forwarder: {
        Name: "ABC Logistics Pvt Ltd",
        Trips: [
          {
            BookingId: "FQ-BK-4582",
            TruckType: "20 FT",
            Destination: "Kollam",
            TripRate: 18000,
            CurrentStatus: "In Queue",
            QueuePosition: 3,
            BookingTime: "20 July 2025, 11:30 AM",
            Transporter: null,
            TruckNumber: null,
            ContactPerson: null,
            ContactNumber: null,
          },
          {
            BookingId: "FQ-BK-1234",
            TruckType: "20 FT",
            Destination: "Kollam",
            TripRate: 18000,
            CurrentStatus: "In Queue",
            QueuePosition: 3,
            BookingTime: "20 July 2025, 11:30 AM",
            Transporter: null,
            TruckNumber: null,
            ContactPerson: null,
            ContactNumber: null,
          },
          {
            BookingId: "FQ-BK-4582",
            TruckType: "20 FT",
            Destination: "Kollam",
            TripRate: 18000,
            CurrentStatus: "Allotted",
            QueuePosition: null,
            BookingTime: "20 July 2025, 11:30 AM",
            Transporter: "ABC Transporter",
            TruckNumber: "KL-07-AB-0000",
            ContactPerson: "Latheef",
            ContactNumber: "9447110022",
          },
          {
            BookingId: "FQ-BK-4582",
            TruckType: "20 FT",
            Destination: "Kozhikkod",
            TripRate: 18000,
            CurrentStatus: "Allotted",
            QueuePosition: null,
            BookingTime: "20 July 2025, 11:30 AM",
            Transporter: "ABC Transporter",
            TruckNumber: "KL-07-AB-1234",
            ContactPerson: "Shibu",
            ContactNumber: "9447110022",
          },
        ],
      },
    },
  });
});

export { getFleet };
